### ISSUE TITLE
Multi-page responses not working

### ISSUE THREAD

**Issue by Pteromungus** [clandriot/jira-node-client#1]
This is a log output of a tool I use which extracts data from JIRA.
As you can see, upon the second request, the parameter "startAt=50" is passed wrongly in the URL query string. The first parameter should follow a "?".

I'm currently using jira-node-client 1.1.0.

```
* try to execute request (https://celfocusjira.atlassian.net/rest/agile/latest/board): 1/10
(node:13448)
* Request OK, code = 200
* try to execute request (https://celfocusjira.atlassian.net/rest/agile/latest/board&startAt=50): 1/5
* AGILE-METRICS: Jira data query error:  { code: 404,
  url: 'https://celfocusjira.atlassian.net/rest/agile/latest/board&startAt=50',
  message: '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>404</status-code><message>null for uri: https://celfocusjira.atlassian.net/rest/agile/latest/board&amp;startAt=50</message></status>' }
```

**Comment by clandriot** [comment]
Hi Pterommungus,
The goal of api is to be used with the Jira search API: <root_url>/rest/api/latest/search?jql=<bla_bla>, and so to return a list of Jira issues.
It is not done to be used with other APIs. This is why the code expect '?' to already be present (as it is already set in search api to set the jql parameter).
